language: node_js
node_js:
- 6
branches:
  only:
  - master
env:
  global:
    secure: A9wgSVN3CqyYzbKuNFHG0HdMvwTi7uXJ00ZSfvSGR5rGLM/P5clTkB5XJofFEpoF1oQMisqvrrNnYAA5nZSYkQV1FXYBgEk0cYkfc9bXx6zeySHhHpc5SndB8Smj8Sv+wraSsYcSMPeNyuIy8hso9C4HBNhZ4WeLP90xwtXgZcX7UL+47OvEFfLPvqdO+wCEU4HtYsM4eeGLwn3XoQu0pxpJESTfQGDJNfvZVP0jgNSagCsjgjrdAsnhq0I+6Z7fpjg5woUe8l/tkFqRiekftPJQD+eVmi/u7fcUmshurp+OpsFEN3CGPo3Q5qrSzUHtIaiDIZcregElax4rbspYKC29PLwpsozJkgVY6FIMwokXUNZqeYYcWQObItAX2gmlBoO8KVP6WFenfVVikffRAbdJgoE30trhMgF5Q5CnXYWb3y2QzF/zz02JmqvJsTVfstEmmZnGrgX5iwH2xbF4iG0X1JXpNVan9zVAex8Sqqt1O6TCO/lfDJBkvtxzsQpavw3ZJtFnEDHNM/L2VQSZ403x0liUoLDXVyHqWjUAr9VlD0YDoEyw1JsHfLAIPkVn4B/5EcGZqrCdmVLQihJpc15mTCgZB7MzH3kiGTXEhFMslXH6vwZ6sqKPWAWeyDceVzCKZeN44DbhR0cYZF8FeDkr0YZea2BAFKx/UNHmVZw=
script:
- npm i git-credential-env -g
- git config credential.helper "env --username=GH_TOKEN"
- git config user.name "Travis CI"
- npm run deploy
